import { createWebHistory, createRouter, RouteRecordRaw } from "vue-router";
import Home from '../views/Home.vue'
import FaleConosco from '../views/fale-conosco/FaleConosco.vue'
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
import Parceiros from '../views/parceiros/Parceiros.vue'
import ParceiroExpandido from '../views/parceiros/expandido/ParceiroExpandido.vue'
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
import QuemSomos from '../views/quem-somos/QuemSomos.vue'
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FEATURE_3068_QuemSomos

const routes: RouteRecordRaw[] = [
  {
    path: "/",
    name: "Home",
    component: Home,
  },
  {
    path: "/fale-conosco",
    name: "FaleConosco",
    component: FaleConosco
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  },
  {
    path: "/parceiros",
    name: "Parceiros",
    component: Parceiros
  },
  {
    path: "/parceiros/:parceiroId",
    name: "ParceiroExpandido",
    component: ParceiroExpandido
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
  },
  {
    path: "/quem-somos",
    name: "QuemSomos",
    component: QuemSomos
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FEATURE_3068_QuemSomos
  }
];

const router = createRouter({
  history: createWebHistory(),
  routes,
});

export default router;