<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
<template> <!-- este é o componente que vai na tela home, o carrosel de empresas parceiras -->
  <section class="container-fluid partners-container ghp">
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
<template>
  <section class="container-fluid partners-container ghp">
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FEATURE_3071_Eventos
    <h1 class="dark-title">EMPRESAS PARCEIRAS</h1>
    <main>
      <div id="partnersCarousel" class="carousel slide carousel-dark" data-bs-ride="carousel" pause="true">
        <div class="carousel-inner" pause="true">
          <div v-for="(logo, index) in logosUrlArray" :key="index" class="carousel-item" :class="{'active': index === 0}">
            <img :src="logo" class="d-block w-100" alt="logo parceiro">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#partnersCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#partnersCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </main>
  </section>
</template>

<script setup lang="ts">

 const props = defineProps<{
   logosUrlArray: string[]
 }>()
</script>

<style scoped lang="scss">
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
  section.partners-container {
    // padding: 40px 200px !important;
    height: 500px;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FEATURE_3071_Eventos
  .carousel-item {
    img {
      min-width: 240px !important;
      margin: auto;
      max-width: 500px;
    }
  }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
  @media (max-width: 768px) {
    section.partners-container {
      h1 {
        font-size: 1.2rem;
      }
    }
  }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
  // @media (max-width: 576px) {
  //   section.partners-container {
  //     padding: 0 !important;
  //   }
  // }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FEATURE_3071_Eventos
</style>